### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused',)) Input:

### ISSUE THREAD

**Issue by SeekPoint** [jingweiz/pytorch-dnc#8]
+- - - - - - - - - - 1 1 1 1 1 1 1 1 - - - -+
+- - - - - - - - - - - - - - 1 1 1 1 - - - -+
+- - - - - - - - - - 1 1 1 1 1 1 1 1 - - - -+
+- - - - - - - - - - 1 1 1 1 1 - - - - - - -+
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/visdom/__init__.py", line 228, in _send
    data=json.dumps(msg),
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7faed051b610>: Failed to establish a new connection: [Errno 111] Connection refused',))
Input:
+- - 1 1 1 - - - 1 1 1 - - - - - - - - - - -+
+- - 1 1 1 1 - 1 1 1 - - - - - - - - - - - -+
+- - - 1 - - 1 1 1 1 - - - - - - - - - - - -+
+- 1 - 1 - 1 1 1 - - 1 - - - - - - - - - - -+

**Comment by jingweiz** [comment]
Hey,
so this means you didn't start a visdom server before running the code. you can simply do: ```python -m visdom.server &``` before you run ```python main.py```, preferrly in another terminal session to avoid the output streams being mixed together
